/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CONTROLADOR;

import MODELO.Usuario;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 59398
 */
public class PRUEBA extends javax.swing.JInternalFrame {


    /**
     * Creates new form PRUEBA
     */
    public PRUEBA() {
        initComponents();
        setModelo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarUsuario = new javax.swing.JButton();
        txtNombreU = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcontra = new javax.swing.JPasswordField();
        btnEliminarUsuario = new javax.swing.JButton();
        txtRol = new javax.swing.JTextField();
        btnModificarUsuario = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuario);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarUsuario.setText("Agregar");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        jPanel1.add(txtNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 150, -1));

        jLabel1.setText("Contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel3.setText("Rol");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        jPanel1.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, -1));

        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        jPanel1.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 130, -1));

        btnModificarUsuario.setText("Modificar");
        btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        int filaSeleccionada = jTableUsuario.getSelectedRow();

        if (filaSeleccionada >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) jTableUsuario.getModel();
            int idUsuario = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 0).toString());
            String nombre = modelo.getValueAt(filaSeleccionada, 1).toString();
            String contrasenia = modelo.getValueAt(filaSeleccionada, 2).toString();
            String roles = modelo.getValueAt(filaSeleccionada, 3).toString();

            UsuarioControlador usuarioControlador = new UsuarioControlador();
            usuarioControlador.eliminarUsuario(idUsuario, nombre, contrasenia, roles);

            modelo.removeRow(filaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar");
        }
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        String nombre = txtNombreU.getText();
        String contrasenia = txtcontra.getText();
        String rolIngresado = txtRol.getText(); 
        Usuario uM = new Usuario(nombre, contrasenia, rolIngresado);

        UsuarioControlador usuarioControlador = new UsuarioControlador();
        usuarioControlador.insertarUsuario(uM);
        listaPersonas.add(uM);
        setDatos(uM);
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        
        int filaSeleccionada = jTableUsuario.getSelectedRow();

        if (filaSeleccionada >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) jTableUsuario.getModel();
            String nombreAntiguo = modelo.getValueAt(filaSeleccionada, 1).toString();
            String contraseniaAntigua = modelo.getValueAt(filaSeleccionada, 2).toString();
            String rolAntiguo = modelo.getValueAt(filaSeleccionada, 3).toString();

            String nuevoNombre = txtNombreU.getText();
            String nuevaContrasenia = txtcontra.getText();
            String nuevosRoles = txtRol.getText();

            if (nuevoNombre.isEmpty() || nuevaContrasenia.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese un nuevo nombre y contraseña");
            } else {
                UsuarioControlador usuarioControlador = new UsuarioControlador();
                usuarioControlador.editarUsuario(nombreAntiguo, contraseniaAntigua, rolAntiguo, nuevoNombre, nuevaContrasenia, nuevosRoles);

                modelo.setValueAt(nuevoNombre, filaSeleccionada, 1);
                modelo.setValueAt(nuevaContrasenia, filaSeleccionada, 2);
                modelo.setValueAt(nuevosRoles, filaSeleccionada, 3);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para editar");
        }


    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    
        String nombreBuscado = txtNombreU.getText();

    if (!nombreBuscado.isEmpty()) {
        UsuarioControlador usuarioControlador = new UsuarioControlador();
        ArrayList<Object[]> resultados = usuarioControlador.buscarUsuarios(nombreBuscado);

        DefaultTableModel modelo = (DefaultTableModel) jTableUsuario.getModel();
        modelo.setRowCount(0);

        if (resultados != null) {
            for (Object[] fila : resultados) {
                modelo.addRow(fila);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al buscar usuarios por nombre");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Ingrese un nombre para buscar");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) jTableUsuario.getModel();
        txtNombreU.setText((String) modelo.getValueAt(jTableUsuario.getSelectedRow(), 1));
        txtcontra.setText((String) modelo.getValueAt(jTableUsuario.getSelectedRow(), 2));
        txtRol.setText((String) modelo.getValueAt(jTableUsuario.getSelectedRow(), 3));
    }//GEN-LAST:event_jTableUsuarioMouseClicked

   private ArrayList<Usuario> listaPersonas = new ArrayList<>();
    private DefaultTableModel modeloUsuario = new DefaultTableModel();
    
              
public void setModelo() {
    
    String[] cabecera = {"Nro.", "Nombres", "Contraseñas", "Roles"};
    modeloUsuario.setColumnIdentifiers(cabecera);

    UsuarioControlador usuarioControlador = new UsuarioControlador();
    ArrayList<Object[]> datos = usuarioControlador.datosUsuarios();

    if (datos != null) {
        for (Object[] fila : datos) {
            modeloUsuario.addRow(fila);
        }
    }

    jTableUsuario.setModel(modeloUsuario);
}

    public void setDatos(Usuario usuario) {
        DefaultTableModel modelo = (DefaultTableModel) jTableUsuario.getModel();
        Object[] fila = new Object[4];

        fila[0] = modelo.getRowCount() + 1;
        fila[1] = usuario.getNombre();
        fila[2] = usuario.getContraseña();
        fila[3] = usuario.getRoles();

        modelo.addRow(fila);
        jTableUsuario.setModel(modelo);
        txtNombreU.setText("");
        txtcontra.setText("");
        txtRol.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField txtNombreU;
    private javax.swing.JTextField txtRol;
    private javax.swing.JPasswordField txtcontra;
    // End of variables declaration//GEN-END:variables
}
